/**
 * generated by Xtext 2.17.1
 */
package com.specmate.cause_effect_patterns.internal.specDSL.impl;

import org.eclipse.emf.ecore.EClass;

import com.specmate.cause_effect_patterns.internal.specDSL.POSTag;
import com.specmate.cause_effect_patterns.internal.specDSL.SpecDSLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>POS Tag</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class POSTagImpl extends TagImpl implements POSTag
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected POSTagImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SpecDSLPackage.Literals.POS_TAG;
  }

} //POSTagImpl
