/**
 * generated by Xtext 2.17.1
 */
package org.xtext.specmate.specDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dependency Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.specmate.specDSL.DependencyRule#getLeftNode <em>Left Node</em>}</li>
 *   <li>{@link org.xtext.specmate.specDSL.DependencyRule#getDTag <em>DTag</em>}</li>
 *   <li>{@link org.xtext.specmate.specDSL.DependencyRule#getRightNode <em>Right Node</em>}</li>
 * </ul>
 *
 * @see org.xtext.specmate.specDSL.SpecDSLPackage#getDependencyRule()
 * @model
 * @generated
 */
public interface DependencyRule extends EObject
{
  /**
   * Returns the value of the '<em><b>Left Node</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Left Node</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left Node</em>' containment reference.
   * @see #setLeftNode(Node)
   * @see org.xtext.specmate.specDSL.SpecDSLPackage#getDependencyRule_LeftNode()
   * @model containment="true"
   * @generated
   */
  Node getLeftNode();

  /**
   * Sets the value of the '{@link org.xtext.specmate.specDSL.DependencyRule#getLeftNode <em>Left Node</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left Node</em>' containment reference.
   * @see #getLeftNode()
   * @generated
   */
  void setLeftNode(Node value);

  /**
   * Returns the value of the '<em><b>DTag</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>DTag</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>DTag</em>' reference.
   * @see #setDTag(DepTag)
   * @see org.xtext.specmate.specDSL.SpecDSLPackage#getDependencyRule_DTag()
   * @model
   * @generated
   */
  DepTag getDTag();

  /**
   * Sets the value of the '{@link org.xtext.specmate.specDSL.DependencyRule#getDTag <em>DTag</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>DTag</em>' reference.
   * @see #getDTag()
   * @generated
   */
  void setDTag(DepTag value);

  /**
   * Returns the value of the '<em><b>Right Node</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Right Node</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right Node</em>' containment reference.
   * @see #setRightNode(EObject)
   * @see org.xtext.specmate.specDSL.SpecDSLPackage#getDependencyRule_RightNode()
   * @model containment="true"
   * @generated
   */
  EObject getRightNode();

  /**
   * Sets the value of the '{@link org.xtext.specmate.specDSL.DependencyRule#getRightNode <em>Right Node</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right Node</em>' containment reference.
   * @see #getRightNode()
   * @generated
   */
  void setRightNode(EObject value);

} // DependencyRule
