/**
 * generated by Xtext 2.17.1
 */
package org.xtext.specmate.specDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dep Tag</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.specmate.specDSL.SpecDSLPackage#getDepTag()
 * @model
 * @generated
 */
public interface DepTag extends Tag
{
} // DepTag
