/**
 * generated by Xtext 2.17.1
 */
package org.xtext.specmate.specDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>POS Tag</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.specmate.specDSL.SpecDSLPackage#getPOSTag()
 * @model
 * @generated
 */
public interface POSTag extends Tag
{
} // POSTag
