/*
 * generated by Xtext 2.17.1
 */
package org.xtext.specmate


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class SpecDSLRuntimeModule extends AbstractSpecDSLRuntimeModule {
}
