/*
 * generated by Xtext 2.17.1
 */
package org.xtext.specmate


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SpecDSLStandaloneSetup extends SpecDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new SpecDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
