/*
 * generated by Xtext 2.17.1
 */
package com.specmate.objectif.internal.validation;

import org.eclipse.xtext.validation.ConfigurableIssueCodesProvider;

public class DSLConfigurableIssueCodesProvider extends ConfigurableIssueCodesProvider {
	protected static final String ISSUE_CODE_PREFIX = "com.specmate.objectif.";

	public static final String DEPRECATED_MODEL_PART = ISSUE_CODE_PREFIX + "deprecatedModelPart";
}
