/**
 * generated by Xtext 2.17.1
 */
package com.specmate.objectif.internal.validation;

import com.specmate.objectif.internal.validation.AbstractDSLValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class DSLValidator extends AbstractDSLValidator {
}
