/**
 * generated by Xtext 2.17.1
 */
package com.specmate.objectif.internal.dSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.specmate.objectif.dSL.Literal#getContent <em>Content</em>}</li>
 * </ul>
 *
 * @see com.specmate.objectif.dSL.DSLPackage#getLiteral()
 * @model
 * @generated
 */
public interface Literal extends EObject
{
  /**
   * Returns the value of the '<em><b>Content</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Content</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Content</em>' attribute list.
   * @see com.specmate.objectif.dSL.DSLPackage#getLiteral_Content()
   * @model unique="false"
   * @generated
   */
  EList<String> getContent();

} // Literal
