/**
 * generated by Xtext 2.17.1
 */
package com.specmate.objectif.internal.dSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>OR Node</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.specmate.objectif.dSL.OR_Node#getNode <em>Node</em>}</li>
 *   <li>{@link com.specmate.objectif.dSL.OR_Node#isOr <em>Or</em>}</li>
 *   <li>{@link com.specmate.objectif.dSL.OR_Node#getSubNode <em>Sub Node</em>}</li>
 * </ul>
 *
 * @see com.specmate.objectif.dSL.DSLPackage#getOR_Node()
 * @model
 * @generated
 */
public interface OR_Node extends EObject
{
  /**
   * Returns the value of the '<em><b>Node</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Node</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Node</em>' containment reference.
   * @see #setNode(AND_Node)
   * @see com.specmate.objectif.dSL.DSLPackage#getOR_Node_Node()
   * @model containment="true"
   * @generated
   */
  AND_Node getNode();

  /**
   * Sets the value of the '{@link com.specmate.objectif.dSL.OR_Node#getNode <em>Node</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Node</em>' containment reference.
   * @see #getNode()
   * @generated
   */
  void setNode(AND_Node value);

  /**
   * Returns the value of the '<em><b>Or</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Or</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Or</em>' attribute.
   * @see #setOr(boolean)
   * @see com.specmate.objectif.dSL.DSLPackage#getOR_Node_Or()
   * @model
   * @generated
   */
  boolean isOr();

  /**
   * Sets the value of the '{@link com.specmate.objectif.dSL.OR_Node#isOr <em>Or</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Or</em>' attribute.
   * @see #isOr()
   * @generated
   */
  void setOr(boolean value);

  /**
   * Returns the value of the '<em><b>Sub Node</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sub Node</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sub Node</em>' containment reference.
   * @see #setSubNode(OR_Node)
   * @see com.specmate.objectif.dSL.DSLPackage#getOR_Node_SubNode()
   * @model containment="true"
   * @generated
   */
  OR_Node getSubNode();

  /**
   * Sets the value of the '{@link com.specmate.objectif.dSL.OR_Node#getSubNode <em>Sub Node</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sub Node</em>' containment reference.
   * @see #getSubNode()
   * @generated
   */
  void setSubNode(OR_Node value);

} // OR_Node
