<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http://specmate.com/20151203_01/model" nsPrefix="com.specmate.model">
  <eSubpackages name="basemodel" nsURI="http://specmate.com/20151203_01/model/basemodel"
      nsPrefix="com.specmate.model.basemodel">
    <eClassifiers xsi:type="ecore:EClass" name="INamed" abstract="true" interface="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IDescribed" abstract="true" interface="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IID" abstract="true" interface="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          iD="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IContentElement" abstract="true" interface="true"
        eSuperTypes="#//basemodel/IID #//basemodel/INamed #//basemodel/IDescribed #//basemodel/IAnnotationContainer"/>
    <eClassifiers xsi:type="ecore:EClass" name="IUIInfo" abstract="true" interface="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IUIContentElement" abstract="true"
        interface="true" eSuperTypes="#//basemodel/IContentElement #//basemodel/IUIInfo"/>
    <eClassifiers xsi:type="ecore:EClass" name="IAnnotationContainer" abstract="true"
        interface="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="annotations" upperBound="-1"
          eType="#//basemodel/IAnnotation" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IAnnotation" abstract="true" interface="true"
        eSuperTypes="#//basemodel/IID"/>
    <eClassifiers xsi:type="ecore:EClass" name="UIAnnotation" eSuperTypes="#//basemodel/IUIInfo #//basemodel/IAnnotation"/>
    <eClassifiers xsi:type="ecore:EClass" name="IGraphNode" abstract="true" interface="true"
        eSuperTypes="#//basemodel/IUIContentElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="predecessors" upperBound="-1"
          eType="#//basemodel/IGraphNode" eOpposite="#//basemodel/IGraphNode/successors"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="successors" upperBound="-1"
          eType="#//basemodel/IGraphNode" eOpposite="#//basemodel/IGraphNode/predecessors"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IGraph" abstract="true" interface="true"
        eSuperTypes="#//basemodel/IContentElement http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eStructuralFeatures xsi:type="ecore:EReference" name="rootNode" lowerBound="1"
          eType="#//basemodel/IGraphNode"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BaseModelNode" eSuperTypes="http://www.eclipse.org/emf/2002/Ecore#//EObject #//basemodel/IAnnotationContainer #//basemodel/IContentElement">
      <eAnnotations source="http://specmate.com/gen">
        <details key="icon" value="fa fa-folder"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="#//basemodel/IContentElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="VariableValue">
      <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="#//basemodel/Variable"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
