<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http://specmate.com/20151203_01/model" nsPrefix="com.specmate.model">
  <eSubpackages name="base" nsURI="http://specmate.com/20170209/model/base" nsPrefix="com.specmate.model.basemodel">
    <eClassifiers xsi:type="ecore:EClass" name="INamed" abstract="true" interface="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://specmate.com/form_meta">
          <details key="shortDesc" value="Name"/>
          <details key="longDesc" value=""/>
          <details key="required" value="true"/>
          <details key="type" value="text"/>
          <details key="position" value="0"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IDescribed" abstract="true" interface="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://specmate.com/form_meta">
          <details key="shortDesc" value="Description"/>
          <details key="longDesc" value=""/>
          <details key="required" value="false"/>
          <details key="type" value="longText"/>
          <details key="rows" value="8"/>
          <details key="position" value="100"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IID" abstract="true" interface="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          iD="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IContentElement" abstract="true" interface="true"
        eSuperTypes="#//base/IID #//base/INamed #//base/IDescribed"/>
    <eClassifiers xsi:type="ecore:EClass" name="IContainer" abstract="true" interface="true"
        eSuperTypes="#//base/IContentElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1"
          eType="#//base/IContentElement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ISpecmateModelObject" abstract="true"
        interface="true" eSuperTypes="#//base/IContainer"/>
    <eClassifiers xsi:type="ecore:EClass" name="Folder" eSuperTypes="#//base/ISpecmateModelObject"/>
    <eClassifiers xsi:type="ecore:EClass" name="IPositionable" abstract="true" interface="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="position" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IExternal">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="extId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="extId2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ISpecmatePositionableModelObject"
        abstract="true" interface="true" eSuperTypes="#//base/ISpecmateModelObject">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="requirements" nsURI="http://specmate.com/20170209/model/requirements"
      nsPrefix="com.specmate.model.requirements">
    <eClassifiers xsi:type="ecore:EClass" name="Requirement" eSuperTypes="#//base/ISpecmateModelObject #//base/IExternal">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfTests" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="tac" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="implementingUnit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="implementingBOTeam" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="implementingITTeam" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="plannedRelease" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CEGModel" eSuperTypes="#//base/ISpecmateModelObject"/>
    <eClassifiers xsi:type="ecore:EClass" name="CEGNode" eSuperTypes="#//base/ISpecmatePositionableModelObject">
      <eAnnotations source="http://specmate.com/form_meta">
        <details key="disabled1" value="name"/>
        <details key="disabled2" value="description"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//requirements/NodeType">
        <eAnnotations source="http://specmate.com/form_meta">
          <details key="shortDesc" value="Type"/>
          <details key="longDesc" value="The type of a node"/>
          <details key="required" value="true"/>
          <details key="type" value="singleSelection"/>
          <details key="values" value="[&quot;AND&quot;, &quot;OR&quot;]"/>
          <details key="position" value="3"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingConnections"
          upperBound="-1" eType="#//requirements/CEGConnection" eOpposite="#//requirements/CEGConnection/source"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="incomingConnections"
          upperBound="-1" eType="#//requirements/CEGConnection" eOpposite="#//requirements/CEGConnection/target"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="variable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://specmate.com/form_meta">
          <details key="shortDesc" value="Variable"/>
          <details key="longDesc" value="The variable of a node"/>
          <details key="required" value="true"/>
          <details key="type" value="text"/>
          <details key="position" value="1"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://specmate.com/form_meta">
          <details key="shortDesc" value="Condition"/>
          <details key="longDesc" value="The condition the variable has to fulfil"/>
          <details key="required" value="true"/>
          <details key="type" value="text"/>
          <details key="position" value="2"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="NodeType">
      <eLiterals name="AND"/>
      <eLiterals name="OR" value="1"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CEGConnection" eSuperTypes="#//base/ISpecmateModelObject">
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//requirements/CEGNode"
          eOpposite="#//requirements/CEGNode/outgoingConnections"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//requirements/CEGNode"
          eOpposite="#//requirements/CEGNode/incomingConnections"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="negate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eAnnotations source="http://specmate.com/form_meta">
          <details key="shortDesc" value="Negate"/>
          <details key="longDesc" value="Negation of this connection"/>
          <details key="type" value="checkbox"/>
          <details key="position" value="1"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="testspecification" nsURI="http://specmate.com/20170409/model/testspecification"
      nsPrefix="com.specmate.model.testspecification">
    <eClassifiers xsi:type="ecore:EClass" name="TestSpecification" eSuperTypes="#//base/IContainer"/>
    <eClassifiers xsi:type="ecore:EClass" name="TestParameter" eSuperTypes="#//base/IContentElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//testspecification/ParameterType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="assignments" upperBound="-1"
          eType="#//testspecification/ParameterAssignment" eOpposite="#//testspecification/ParameterAssignment/parameter"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TestCase" eSuperTypes="#//base/IContainer #//base/IPositionable"/>
    <eClassifiers xsi:type="ecore:EClass" name="ParameterAssignment" eSuperTypes="#//base/IContentElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" eType="#//testspecification/TestParameter"
          eOpposite="#//testspecification/TestParameter/assignments"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ParameterType">
      <eLiterals name="INPUT"/>
      <eLiterals name="OUTPUT" value="1"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TestProcedure" eSuperTypes="#//base/IContainer #//base/IExternal">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isRegressionTest" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eAnnotations source="http://specmate.com/form_meta">
          <details key="shortDesc" value="Regression Test"/>
          <details key="type" value="checkbox"/>
          <details key="position" value="3"/>
          <details key="longDesc" value=""/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TestStep" eSuperTypes="#//base/IContentElement #//base/IPositionable">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="expectedOutcome" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="referencedTestParameters"
          upperBound="-1" eType="#//testspecification/TestParameter"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="processes" nsURI="http://specmate.com/20170409/model/processes"
      nsPrefix="com.specmate.model.processes">
    <eClassifiers xsi:type="ecore:EClass" name="Process" eSuperTypes="#//base/IContainer"/>
    <eClassifiers xsi:type="ecore:EClass" name="ProcessNode" abstract="true" eSuperTypes="#//base/ISpecmatePositionableModelObject">
      <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingConnections"
          upperBound="-1" eType="#//processes/ProcessConnection" eOpposite="#//processes/ProcessConnection/source"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="incomingConnections"
          upperBound="-1" eType="#//processes/ProcessConnection" eOpposite="#//processes/ProcessConnection/target"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ProcessStep" eSuperTypes="#//processes/ProcessNode"/>
    <eClassifiers xsi:type="ecore:EClass" name="ProcessDecision" eSuperTypes="#//processes/ProcessNode"/>
    <eClassifiers xsi:type="ecore:EClass" name="ProcessConnection" eSuperTypes="#//base/ISpecmateModelObject">
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//processes/ProcessNode"
          eOpposite="#//processes/ProcessNode/outgoingConnections"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//processes/ProcessNode"
          eOpposite="#//processes/ProcessNode/incomingConnections"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
