<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http://specmate.com/20151203_01/model" nsPrefix="com.specmate.model">
  <eSubpackages name="base" nsURI="http://specmate.com/20170209/model/base" nsPrefix="com.specmate.model.basemodel">
    <eClassifiers xsi:type="ecore:EClass" name="INamed" abstract="true" interface="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IDescribed" abstract="true" interface="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IID" abstract="true" interface="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          iD="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IContentElement" abstract="true" interface="true"
        eSuperTypes="#//base/IID #//base/INamed #//base/IDescribed"/>
    <eClassifiers xsi:type="ecore:EClass" name="IContainer" abstract="true" interface="true"
        eSuperTypes="#//base/IContentElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1"
          eType="#//base/IContentElement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ISpecmateModelObject" eSuperTypes="#//base/IContainer #//base/IContentElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="Folder" eSuperTypes="#//base/ISpecmateModelObject"/>
  </eSubpackages>
  <eSubpackages name="requirements" nsURI="http://specmate.com/20170209/model/requirements"
      nsPrefix="com.specmate.model.requirements">
    <eClassifiers xsi:type="ecore:EClass" name="Requirement" eSuperTypes="#//base/ISpecmateModelObject"/>
  </eSubpackages>
</ecore:EPackage>
