/**
 * generated by Xtext 2.17.1
 */
package com.specmate.objectif.internal;

import com.specmate.objectif.internal.AbstractDSLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class DSLRuntimeModule extends AbstractDSLRuntimeModule {
}
