/**
 * generated by Xtext 2.17.1
 */
package com.specmate.cause_effect_patterns.internal.specDSL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see com.specmate.cause_effect_patterns.specDSL.SpecDSLFactory
 * @model kind="package"
 * @generated
 */
public interface SpecDSLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "specDSL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.specmate.com/cause_effect_patterns/SpecDSL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "specDSL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SpecDSLPackage eINSTANCE = com.specmate.cause_effect_patterns.internal.specDSL.impl.SpecDSLPackageImpl.init();

  /**
   * The meta object id for the '{@link com.specmate.cause_effect_patterns.specDSL.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.specmate.cause_effect_patterns.specDSL.impl.ModelImpl
   * @see com.specmate.cause_effect_patterns.specDSL.impl.SpecDSLPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.specmate.cause_effect_patterns.specDSL.impl.AbstractElementImpl <em>Abstract Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.specmate.cause_effect_patterns.specDSL.impl.AbstractElementImpl
   * @see com.specmate.cause_effect_patterns.specDSL.impl.SpecDSLPackageImpl#getAbstractElement()
   * @generated
   */
  int ABSTRACT_ELEMENT = 1;

  /**
   * The number of structural features of the '<em>Abstract Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_ELEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link com.specmate.cause_effect_patterns.specDSL.impl.ImportImpl <em>Import</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.specmate.cause_effect_patterns.specDSL.impl.ImportImpl
   * @see com.specmate.cause_effect_patterns.specDSL.impl.SpecDSLPackageImpl#getImport()
   * @generated
   */
  int IMPORT = 2;

  /**
   * The feature id for the '<em><b>Imported Namespace</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT__IMPORTED_NAMESPACE = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Import</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.specmate.cause_effect_patterns.specDSL.impl.PosDefImpl <em>Pos Def</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.specmate.cause_effect_patterns.specDSL.impl.PosDefImpl
   * @see com.specmate.cause_effect_patterns.specDSL.impl.SpecDSLPackageImpl#getPosDef()
   * @generated
   */
  int POS_DEF = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POS_DEF__NAME = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Tags</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POS_DEF__TAGS = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Pos Def</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POS_DEF_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link com.specmate.cause_effect_patterns.specDSL.impl.TagImpl <em>Tag</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.specmate.cause_effect_patterns.specDSL.impl.TagImpl
   * @see com.specmate.cause_effect_patterns.specDSL.impl.SpecDSLPackageImpl#getTag()
   * @generated
   */
  int TAG = 16;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TAG__NAME = 0;

  /**
   * The feature id for the '<em><b>Tagname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TAG__TAGNAME = 1;

  /**
   * The number of structural features of the '<em>Tag</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TAG_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.specmate.cause_effect_patterns.specDSL.impl.POSTagImpl <em>POS Tag</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.specmate.cause_effect_patterns.specDSL.impl.POSTagImpl
   * @see com.specmate.cause_effect_patterns.specDSL.impl.SpecDSLPackageImpl#getPOSTag()
   * @generated
   */
  int POS_TAG = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POS_TAG__NAME = TAG__NAME;

  /**
   * The feature id for the '<em><b>Tagname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POS_TAG__TAGNAME = TAG__TAGNAME;

  /**
   * The number of structural features of the '<em>POS Tag</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POS_TAG_FEATURE_COUNT = TAG_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link com.specmate.cause_effect_patterns.specDSL.impl.DepDefImpl <em>Dep Def</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.specmate.cause_effect_patterns.specDSL.impl.DepDefImpl
   * @see com.specmate.cause_effect_patterns.specDSL.impl.SpecDSLPackageImpl#getDepDef()
   * @generated
   */
  int DEP_DEF = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEP_DEF__NAME = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Tags</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEP_DEF__TAGS = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Dep Def</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEP_DEF_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link com.specmate.cause_effect_patterns.specDSL.impl.DepTagImpl <em>Dep Tag</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.specmate.cause_effect_patterns.specDSL.impl.DepTagImpl
   * @see com.specmate.cause_effect_patterns.specDSL.impl.SpecDSLPackageImpl#getDepTag()
   * @generated
   */
  int DEP_TAG = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEP_TAG__NAME = TAG__NAME;

  /**
   * The feature id for the '<em><b>Tagname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEP_TAG__TAGNAME = TAG__TAGNAME;

  /**
   * The number of structural features of the '<em>Dep Tag</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEP_TAG_FEATURE_COUNT = TAG_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link com.specmate.cause_effect_patterns.specDSL.impl.TreeDefImpl <em>Tree Def</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.specmate.cause_effect_patterns.specDSL.impl.TreeDefImpl
   * @see com.specmate.cause_effect_patterns.specDSL.impl.SpecDSLPackageImpl#getTreeDef()
   * @generated
   */
  int TREE_DEF = 7;

  /**
   * The feature id for the '<em><b>Trees</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TREE_DEF__TREES = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Tree Def</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TREE_DEF_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.specmate.cause_effect_patterns.specDSL.impl.TreeTagImpl <em>Tree Tag</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.specmate.cause_effect_patterns.specDSL.impl.TreeTagImpl
   * @see com.specmate.cause_effect_patterns.specDSL.impl.SpecDSLPackageImpl#getTreeTag()
   * @generated
   */
  int TREE_TAG = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TREE_TAG__NAME = 0;

  /**
   * The number of structural features of the '<em>Tree Tag</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TREE_TAG_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.specmate.cause_effect_patterns.specDSL.impl.RuleImpl <em>Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.specmate.cause_effect_patterns.specDSL.impl.RuleImpl
   * @see com.specmate.cause_effect_patterns.specDSL.impl.SpecDSLPackageImpl#getRule()
   * @generated
   */
  int RULE = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__NAME = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Dependencies</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__DEPENDENCIES = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link com.specmate.cause_effect_patterns.specDSL.impl.DependencyRuleImpl <em>Dependency Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.specmate.cause_effect_patterns.specDSL.impl.DependencyRuleImpl
   * @see com.specmate.cause_effect_patterns.specDSL.impl.SpecDSLPackageImpl#getDependencyRule()
   * @generated
   */
  int DEPENDENCY_RULE = 10;

  /**
   * The feature id for the '<em><b>Left Node</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPENDENCY_RULE__LEFT_NODE = 0;

  /**
   * The feature id for the '<em><b>DTag</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPENDENCY_RULE__DTAG = 1;

  /**
   * The feature id for the '<em><b>Right Node</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPENDENCY_RULE__RIGHT_NODE = 2;

  /**
   * The number of structural features of the '<em>Dependency Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPENDENCY_RULE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link com.specmate.cause_effect_patterns.specDSL.impl.NodeImpl <em>Node</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.specmate.cause_effect_patterns.specDSL.impl.NodeImpl
   * @see com.specmate.cause_effect_patterns.specDSL.impl.SpecDSLPackageImpl#getNode()
   * @generated
   */
  int NODE = 11;

  /**
   * The number of structural features of the '<em>Node</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link com.specmate.cause_effect_patterns.specDSL.impl.OptionNodeImpl <em>Option Node</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.specmate.cause_effect_patterns.specDSL.impl.OptionNodeImpl
   * @see com.specmate.cause_effect_patterns.specDSL.impl.SpecDSLPackageImpl#getOptionNode()
   * @generated
   */
  int OPTION_NODE = 12;

  /**
   * The feature id for the '<em><b>Left Node</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTION_NODE__LEFT_NODE = NODE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right Nodes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTION_NODE__RIGHT_NODES = NODE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Option Node</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTION_NODE_FEATURE_COUNT = NODE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link com.specmate.cause_effect_patterns.specDSL.impl.TreeNodeImpl <em>Tree Node</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.specmate.cause_effect_patterns.specDSL.impl.TreeNodeImpl
   * @see com.specmate.cause_effect_patterns.specDSL.impl.SpecDSLPackageImpl#getTreeNode()
   * @generated
   */
  int TREE_NODE = 13;

  /**
   * The feature id for the '<em><b>PTag</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TREE_NODE__PTAG = NODE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Expr</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TREE_NODE__EXPR = NODE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Any Match</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TREE_NODE__ANY_MATCH = NODE_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Tree</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TREE_NODE__TREE = NODE_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Tree Node</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TREE_NODE_FEATURE_COUNT = NODE_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link com.specmate.cause_effect_patterns.specDSL.impl.ExplicitNodeImpl <em>Explicit Node</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.specmate.cause_effect_patterns.specDSL.impl.ExplicitNodeImpl
   * @see com.specmate.cause_effect_patterns.specDSL.impl.SpecDSLPackageImpl#getExplicitNode()
   * @generated
   */
  int EXPLICIT_NODE = 14;

  /**
   * The feature id for the '<em><b>PTag</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPLICIT_NODE__PTAG = NODE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Case Sensitive</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPLICIT_NODE__CASE_SENSITIVE = NODE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Expr</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPLICIT_NODE__EXPR = NODE_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Any Match</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPLICIT_NODE__ANY_MATCH = NODE_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Explicit Node</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPLICIT_NODE_FEATURE_COUNT = NODE_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link com.specmate.cause_effect_patterns.specDSL.impl.SubtreeImpl <em>Subtree</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.specmate.cause_effect_patterns.specDSL.impl.SubtreeImpl
   * @see com.specmate.cause_effect_patterns.specDSL.impl.SpecDSLPackageImpl#getSubtree()
   * @generated
   */
  int SUBTREE = 15;

  /**
   * The feature id for the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBTREE__NAME = 0;

  /**
   * The number of structural features of the '<em>Subtree</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBTREE_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link com.specmate.cause_effect_patterns.specDSL.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see com.specmate.cause_effect_patterns.specDSL.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link com.specmate.cause_effect_patterns.specDSL.Model#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see com.specmate.cause_effect_patterns.specDSL.Model#getElements()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Elements();

  /**
   * Returns the meta object for class '{@link com.specmate.cause_effect_patterns.specDSL.AbstractElement <em>Abstract Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Abstract Element</em>'.
   * @see com.specmate.cause_effect_patterns.specDSL.AbstractElement
   * @generated
   */
  EClass getAbstractElement();

  /**
   * Returns the meta object for class '{@link com.specmate.cause_effect_patterns.specDSL.Import <em>Import</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Import</em>'.
   * @see com.specmate.cause_effect_patterns.specDSL.Import
   * @generated
   */
  EClass getImport();

  /**
   * Returns the meta object for the attribute '{@link com.specmate.cause_effect_patterns.specDSL.Import#getImportedNamespace <em>Imported Namespace</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Imported Namespace</em>'.
   * @see com.specmate.cause_effect_patterns.specDSL.Import#getImportedNamespace()
   * @see #getImport()
   * @generated
   */
  EAttribute getImport_ImportedNamespace();

  /**
   * Returns the meta object for class '{@link com.specmate.cause_effect_patterns.specDSL.PosDef <em>Pos Def</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Pos Def</em>'.
   * @see com.specmate.cause_effect_patterns.specDSL.PosDef
   * @generated
   */
  EClass getPosDef();

  /**
   * Returns the meta object for the attribute '{@link com.specmate.cause_effect_patterns.specDSL.PosDef#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.specmate.cause_effect_patterns.specDSL.PosDef#getName()
   * @see #getPosDef()
   * @generated
   */
  EAttribute getPosDef_Name();

  /**
   * Returns the meta object for the containment reference list '{@link com.specmate.cause_effect_patterns.specDSL.PosDef#getTags <em>Tags</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Tags</em>'.
   * @see com.specmate.cause_effect_patterns.specDSL.PosDef#getTags()
   * @see #getPosDef()
   * @generated
   */
  EReference getPosDef_Tags();

  /**
   * Returns the meta object for class '{@link com.specmate.cause_effect_patterns.specDSL.POSTag <em>POS Tag</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>POS Tag</em>'.
   * @see com.specmate.cause_effect_patterns.specDSL.POSTag
   * @generated
   */
  EClass getPOSTag();

  /**
   * Returns the meta object for class '{@link com.specmate.cause_effect_patterns.specDSL.DepDef <em>Dep Def</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Dep Def</em>'.
   * @see com.specmate.cause_effect_patterns.specDSL.DepDef
   * @generated
   */
  EClass getDepDef();

  /**
   * Returns the meta object for the attribute '{@link com.specmate.cause_effect_patterns.specDSL.DepDef#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.specmate.cause_effect_patterns.specDSL.DepDef#getName()
   * @see #getDepDef()
   * @generated
   */
  EAttribute getDepDef_Name();

  /**
   * Returns the meta object for the containment reference list '{@link com.specmate.cause_effect_patterns.specDSL.DepDef#getTags <em>Tags</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Tags</em>'.
   * @see com.specmate.cause_effect_patterns.specDSL.DepDef#getTags()
   * @see #getDepDef()
   * @generated
   */
  EReference getDepDef_Tags();

  /**
   * Returns the meta object for class '{@link com.specmate.cause_effect_patterns.specDSL.DepTag <em>Dep Tag</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Dep Tag</em>'.
   * @see com.specmate.cause_effect_patterns.specDSL.DepTag
   * @generated
   */
  EClass getDepTag();

  /**
   * Returns the meta object for class '{@link com.specmate.cause_effect_patterns.specDSL.TreeDef <em>Tree Def</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tree Def</em>'.
   * @see com.specmate.cause_effect_patterns.specDSL.TreeDef
   * @generated
   */
  EClass getTreeDef();

  /**
   * Returns the meta object for the containment reference list '{@link com.specmate.cause_effect_patterns.specDSL.TreeDef#getTrees <em>Trees</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Trees</em>'.
   * @see com.specmate.cause_effect_patterns.specDSL.TreeDef#getTrees()
   * @see #getTreeDef()
   * @generated
   */
  EReference getTreeDef_Trees();

  /**
   * Returns the meta object for class '{@link com.specmate.cause_effect_patterns.specDSL.TreeTag <em>Tree Tag</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tree Tag</em>'.
   * @see com.specmate.cause_effect_patterns.specDSL.TreeTag
   * @generated
   */
  EClass getTreeTag();

  /**
   * Returns the meta object for the attribute '{@link com.specmate.cause_effect_patterns.specDSL.TreeTag#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.specmate.cause_effect_patterns.specDSL.TreeTag#getName()
   * @see #getTreeTag()
   * @generated
   */
  EAttribute getTreeTag_Name();

  /**
   * Returns the meta object for class '{@link com.specmate.cause_effect_patterns.specDSL.Rule <em>Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rule</em>'.
   * @see com.specmate.cause_effect_patterns.specDSL.Rule
   * @generated
   */
  EClass getRule();

  /**
   * Returns the meta object for the attribute '{@link com.specmate.cause_effect_patterns.specDSL.Rule#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.specmate.cause_effect_patterns.specDSL.Rule#getName()
   * @see #getRule()
   * @generated
   */
  EAttribute getRule_Name();

  /**
   * Returns the meta object for the containment reference list '{@link com.specmate.cause_effect_patterns.specDSL.Rule#getDependencies <em>Dependencies</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Dependencies</em>'.
   * @see com.specmate.cause_effect_patterns.specDSL.Rule#getDependencies()
   * @see #getRule()
   * @generated
   */
  EReference getRule_Dependencies();

  /**
   * Returns the meta object for class '{@link com.specmate.cause_effect_patterns.specDSL.DependencyRule <em>Dependency Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Dependency Rule</em>'.
   * @see com.specmate.cause_effect_patterns.specDSL.DependencyRule
   * @generated
   */
  EClass getDependencyRule();

  /**
   * Returns the meta object for the containment reference '{@link com.specmate.cause_effect_patterns.specDSL.DependencyRule#getLeftNode <em>Left Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left Node</em>'.
   * @see com.specmate.cause_effect_patterns.specDSL.DependencyRule#getLeftNode()
   * @see #getDependencyRule()
   * @generated
   */
  EReference getDependencyRule_LeftNode();

  /**
   * Returns the meta object for the reference '{@link com.specmate.cause_effect_patterns.specDSL.DependencyRule#getDTag <em>DTag</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>DTag</em>'.
   * @see com.specmate.cause_effect_patterns.specDSL.DependencyRule#getDTag()
   * @see #getDependencyRule()
   * @generated
   */
  EReference getDependencyRule_DTag();

  /**
   * Returns the meta object for the containment reference '{@link com.specmate.cause_effect_patterns.specDSL.DependencyRule#getRightNode <em>Right Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right Node</em>'.
   * @see com.specmate.cause_effect_patterns.specDSL.DependencyRule#getRightNode()
   * @see #getDependencyRule()
   * @generated
   */
  EReference getDependencyRule_RightNode();

  /**
   * Returns the meta object for class '{@link com.specmate.cause_effect_patterns.specDSL.Node <em>Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Node</em>'.
   * @see com.specmate.cause_effect_patterns.specDSL.Node
   * @generated
   */
  EClass getNode();

  /**
   * Returns the meta object for class '{@link com.specmate.cause_effect_patterns.specDSL.OptionNode <em>Option Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Option Node</em>'.
   * @see com.specmate.cause_effect_patterns.specDSL.OptionNode
   * @generated
   */
  EClass getOptionNode();

  /**
   * Returns the meta object for the containment reference '{@link com.specmate.cause_effect_patterns.specDSL.OptionNode#getLeftNode <em>Left Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left Node</em>'.
   * @see com.specmate.cause_effect_patterns.specDSL.OptionNode#getLeftNode()
   * @see #getOptionNode()
   * @generated
   */
  EReference getOptionNode_LeftNode();

  /**
   * Returns the meta object for the containment reference list '{@link com.specmate.cause_effect_patterns.specDSL.OptionNode#getRightNodes <em>Right Nodes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Right Nodes</em>'.
   * @see com.specmate.cause_effect_patterns.specDSL.OptionNode#getRightNodes()
   * @see #getOptionNode()
   * @generated
   */
  EReference getOptionNode_RightNodes();

  /**
   * Returns the meta object for class '{@link com.specmate.cause_effect_patterns.specDSL.TreeNode <em>Tree Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tree Node</em>'.
   * @see com.specmate.cause_effect_patterns.specDSL.TreeNode
   * @generated
   */
  EClass getTreeNode();

  /**
   * Returns the meta object for the reference '{@link com.specmate.cause_effect_patterns.specDSL.TreeNode#getPTag <em>PTag</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>PTag</em>'.
   * @see com.specmate.cause_effect_patterns.specDSL.TreeNode#getPTag()
   * @see #getTreeNode()
   * @generated
   */
  EReference getTreeNode_PTag();

  /**
   * Returns the meta object for the attribute '{@link com.specmate.cause_effect_patterns.specDSL.TreeNode#getExpr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Expr</em>'.
   * @see com.specmate.cause_effect_patterns.specDSL.TreeNode#getExpr()
   * @see #getTreeNode()
   * @generated
   */
  EAttribute getTreeNode_Expr();

  /**
   * Returns the meta object for the attribute '{@link com.specmate.cause_effect_patterns.specDSL.TreeNode#isAnyMatch <em>Any Match</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Any Match</em>'.
   * @see com.specmate.cause_effect_patterns.specDSL.TreeNode#isAnyMatch()
   * @see #getTreeNode()
   * @generated
   */
  EAttribute getTreeNode_AnyMatch();

  /**
   * Returns the meta object for the containment reference '{@link com.specmate.cause_effect_patterns.specDSL.TreeNode#getTree <em>Tree</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Tree</em>'.
   * @see com.specmate.cause_effect_patterns.specDSL.TreeNode#getTree()
   * @see #getTreeNode()
   * @generated
   */
  EReference getTreeNode_Tree();

  /**
   * Returns the meta object for class '{@link com.specmate.cause_effect_patterns.specDSL.ExplicitNode <em>Explicit Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Explicit Node</em>'.
   * @see com.specmate.cause_effect_patterns.specDSL.ExplicitNode
   * @generated
   */
  EClass getExplicitNode();

  /**
   * Returns the meta object for the reference '{@link com.specmate.cause_effect_patterns.specDSL.ExplicitNode#getPTag <em>PTag</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>PTag</em>'.
   * @see com.specmate.cause_effect_patterns.specDSL.ExplicitNode#getPTag()
   * @see #getExplicitNode()
   * @generated
   */
  EReference getExplicitNode_PTag();

  /**
   * Returns the meta object for the attribute '{@link com.specmate.cause_effect_patterns.specDSL.ExplicitNode#isCaseSensitive <em>Case Sensitive</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Case Sensitive</em>'.
   * @see com.specmate.cause_effect_patterns.specDSL.ExplicitNode#isCaseSensitive()
   * @see #getExplicitNode()
   * @generated
   */
  EAttribute getExplicitNode_CaseSensitive();

  /**
   * Returns the meta object for the attribute '{@link com.specmate.cause_effect_patterns.specDSL.ExplicitNode#getExpr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Expr</em>'.
   * @see com.specmate.cause_effect_patterns.specDSL.ExplicitNode#getExpr()
   * @see #getExplicitNode()
   * @generated
   */
  EAttribute getExplicitNode_Expr();

  /**
   * Returns the meta object for the attribute '{@link com.specmate.cause_effect_patterns.specDSL.ExplicitNode#isAnyMatch <em>Any Match</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Any Match</em>'.
   * @see com.specmate.cause_effect_patterns.specDSL.ExplicitNode#isAnyMatch()
   * @see #getExplicitNode()
   * @generated
   */
  EAttribute getExplicitNode_AnyMatch();

  /**
   * Returns the meta object for class '{@link com.specmate.cause_effect_patterns.specDSL.Subtree <em>Subtree</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Subtree</em>'.
   * @see com.specmate.cause_effect_patterns.specDSL.Subtree
   * @generated
   */
  EClass getSubtree();

  /**
   * Returns the meta object for the reference '{@link com.specmate.cause_effect_patterns.specDSL.Subtree#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Name</em>'.
   * @see com.specmate.cause_effect_patterns.specDSL.Subtree#getName()
   * @see #getSubtree()
   * @generated
   */
  EReference getSubtree_Name();

  /**
   * Returns the meta object for class '{@link com.specmate.cause_effect_patterns.specDSL.Tag <em>Tag</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tag</em>'.
   * @see com.specmate.cause_effect_patterns.specDSL.Tag
   * @generated
   */
  EClass getTag();

  /**
   * Returns the meta object for the attribute '{@link com.specmate.cause_effect_patterns.specDSL.Tag#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.specmate.cause_effect_patterns.specDSL.Tag#getName()
   * @see #getTag()
   * @generated
   */
  EAttribute getTag_Name();

  /**
   * Returns the meta object for the attribute '{@link com.specmate.cause_effect_patterns.specDSL.Tag#getTagname <em>Tagname</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tagname</em>'.
   * @see com.specmate.cause_effect_patterns.specDSL.Tag#getTagname()
   * @see #getTag()
   * @generated
   */
  EAttribute getTag_Tagname();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  SpecDSLFactory getSpecDSLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link com.specmate.cause_effect_patterns.specDSL.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.specmate.cause_effect_patterns.specDSL.impl.ModelImpl
     * @see com.specmate.cause_effect_patterns.specDSL.impl.SpecDSLPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__ELEMENTS = eINSTANCE.getModel_Elements();

    /**
     * The meta object literal for the '{@link com.specmate.cause_effect_patterns.specDSL.impl.AbstractElementImpl <em>Abstract Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.specmate.cause_effect_patterns.specDSL.impl.AbstractElementImpl
     * @see com.specmate.cause_effect_patterns.specDSL.impl.SpecDSLPackageImpl#getAbstractElement()
     * @generated
     */
    EClass ABSTRACT_ELEMENT = eINSTANCE.getAbstractElement();

    /**
     * The meta object literal for the '{@link com.specmate.cause_effect_patterns.specDSL.impl.ImportImpl <em>Import</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.specmate.cause_effect_patterns.specDSL.impl.ImportImpl
     * @see com.specmate.cause_effect_patterns.specDSL.impl.SpecDSLPackageImpl#getImport()
     * @generated
     */
    EClass IMPORT = eINSTANCE.getImport();

    /**
     * The meta object literal for the '<em><b>Imported Namespace</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IMPORT__IMPORTED_NAMESPACE = eINSTANCE.getImport_ImportedNamespace();

    /**
     * The meta object literal for the '{@link com.specmate.cause_effect_patterns.specDSL.impl.PosDefImpl <em>Pos Def</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.specmate.cause_effect_patterns.specDSL.impl.PosDefImpl
     * @see com.specmate.cause_effect_patterns.specDSL.impl.SpecDSLPackageImpl#getPosDef()
     * @generated
     */
    EClass POS_DEF = eINSTANCE.getPosDef();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute POS_DEF__NAME = eINSTANCE.getPosDef_Name();

    /**
     * The meta object literal for the '<em><b>Tags</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference POS_DEF__TAGS = eINSTANCE.getPosDef_Tags();

    /**
     * The meta object literal for the '{@link com.specmate.cause_effect_patterns.specDSL.impl.POSTagImpl <em>POS Tag</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.specmate.cause_effect_patterns.specDSL.impl.POSTagImpl
     * @see com.specmate.cause_effect_patterns.specDSL.impl.SpecDSLPackageImpl#getPOSTag()
     * @generated
     */
    EClass POS_TAG = eINSTANCE.getPOSTag();

    /**
     * The meta object literal for the '{@link com.specmate.cause_effect_patterns.specDSL.impl.DepDefImpl <em>Dep Def</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.specmate.cause_effect_patterns.specDSL.impl.DepDefImpl
     * @see com.specmate.cause_effect_patterns.specDSL.impl.SpecDSLPackageImpl#getDepDef()
     * @generated
     */
    EClass DEP_DEF = eINSTANCE.getDepDef();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEP_DEF__NAME = eINSTANCE.getDepDef_Name();

    /**
     * The meta object literal for the '<em><b>Tags</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEP_DEF__TAGS = eINSTANCE.getDepDef_Tags();

    /**
     * The meta object literal for the '{@link com.specmate.cause_effect_patterns.specDSL.impl.DepTagImpl <em>Dep Tag</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.specmate.cause_effect_patterns.specDSL.impl.DepTagImpl
     * @see com.specmate.cause_effect_patterns.specDSL.impl.SpecDSLPackageImpl#getDepTag()
     * @generated
     */
    EClass DEP_TAG = eINSTANCE.getDepTag();

    /**
     * The meta object literal for the '{@link com.specmate.cause_effect_patterns.specDSL.impl.TreeDefImpl <em>Tree Def</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.specmate.cause_effect_patterns.specDSL.impl.TreeDefImpl
     * @see com.specmate.cause_effect_patterns.specDSL.impl.SpecDSLPackageImpl#getTreeDef()
     * @generated
     */
    EClass TREE_DEF = eINSTANCE.getTreeDef();

    /**
     * The meta object literal for the '<em><b>Trees</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TREE_DEF__TREES = eINSTANCE.getTreeDef_Trees();

    /**
     * The meta object literal for the '{@link com.specmate.cause_effect_patterns.specDSL.impl.TreeTagImpl <em>Tree Tag</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.specmate.cause_effect_patterns.specDSL.impl.TreeTagImpl
     * @see com.specmate.cause_effect_patterns.specDSL.impl.SpecDSLPackageImpl#getTreeTag()
     * @generated
     */
    EClass TREE_TAG = eINSTANCE.getTreeTag();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TREE_TAG__NAME = eINSTANCE.getTreeTag_Name();

    /**
     * The meta object literal for the '{@link com.specmate.cause_effect_patterns.specDSL.impl.RuleImpl <em>Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.specmate.cause_effect_patterns.specDSL.impl.RuleImpl
     * @see com.specmate.cause_effect_patterns.specDSL.impl.SpecDSLPackageImpl#getRule()
     * @generated
     */
    EClass RULE = eINSTANCE.getRule();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULE__NAME = eINSTANCE.getRule_Name();

    /**
     * The meta object literal for the '<em><b>Dependencies</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE__DEPENDENCIES = eINSTANCE.getRule_Dependencies();

    /**
     * The meta object literal for the '{@link com.specmate.cause_effect_patterns.specDSL.impl.DependencyRuleImpl <em>Dependency Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.specmate.cause_effect_patterns.specDSL.impl.DependencyRuleImpl
     * @see com.specmate.cause_effect_patterns.specDSL.impl.SpecDSLPackageImpl#getDependencyRule()
     * @generated
     */
    EClass DEPENDENCY_RULE = eINSTANCE.getDependencyRule();

    /**
     * The meta object literal for the '<em><b>Left Node</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEPENDENCY_RULE__LEFT_NODE = eINSTANCE.getDependencyRule_LeftNode();

    /**
     * The meta object literal for the '<em><b>DTag</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEPENDENCY_RULE__DTAG = eINSTANCE.getDependencyRule_DTag();

    /**
     * The meta object literal for the '<em><b>Right Node</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEPENDENCY_RULE__RIGHT_NODE = eINSTANCE.getDependencyRule_RightNode();

    /**
     * The meta object literal for the '{@link com.specmate.cause_effect_patterns.specDSL.impl.NodeImpl <em>Node</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.specmate.cause_effect_patterns.specDSL.impl.NodeImpl
     * @see com.specmate.cause_effect_patterns.specDSL.impl.SpecDSLPackageImpl#getNode()
     * @generated
     */
    EClass NODE = eINSTANCE.getNode();

    /**
     * The meta object literal for the '{@link com.specmate.cause_effect_patterns.specDSL.impl.OptionNodeImpl <em>Option Node</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.specmate.cause_effect_patterns.specDSL.impl.OptionNodeImpl
     * @see com.specmate.cause_effect_patterns.specDSL.impl.SpecDSLPackageImpl#getOptionNode()
     * @generated
     */
    EClass OPTION_NODE = eINSTANCE.getOptionNode();

    /**
     * The meta object literal for the '<em><b>Left Node</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPTION_NODE__LEFT_NODE = eINSTANCE.getOptionNode_LeftNode();

    /**
     * The meta object literal for the '<em><b>Right Nodes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPTION_NODE__RIGHT_NODES = eINSTANCE.getOptionNode_RightNodes();

    /**
     * The meta object literal for the '{@link com.specmate.cause_effect_patterns.specDSL.impl.TreeNodeImpl <em>Tree Node</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.specmate.cause_effect_patterns.specDSL.impl.TreeNodeImpl
     * @see com.specmate.cause_effect_patterns.specDSL.impl.SpecDSLPackageImpl#getTreeNode()
     * @generated
     */
    EClass TREE_NODE = eINSTANCE.getTreeNode();

    /**
     * The meta object literal for the '<em><b>PTag</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TREE_NODE__PTAG = eINSTANCE.getTreeNode_PTag();

    /**
     * The meta object literal for the '<em><b>Expr</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TREE_NODE__EXPR = eINSTANCE.getTreeNode_Expr();

    /**
     * The meta object literal for the '<em><b>Any Match</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TREE_NODE__ANY_MATCH = eINSTANCE.getTreeNode_AnyMatch();

    /**
     * The meta object literal for the '<em><b>Tree</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TREE_NODE__TREE = eINSTANCE.getTreeNode_Tree();

    /**
     * The meta object literal for the '{@link com.specmate.cause_effect_patterns.specDSL.impl.ExplicitNodeImpl <em>Explicit Node</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.specmate.cause_effect_patterns.specDSL.impl.ExplicitNodeImpl
     * @see com.specmate.cause_effect_patterns.specDSL.impl.SpecDSLPackageImpl#getExplicitNode()
     * @generated
     */
    EClass EXPLICIT_NODE = eINSTANCE.getExplicitNode();

    /**
     * The meta object literal for the '<em><b>PTag</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPLICIT_NODE__PTAG = eINSTANCE.getExplicitNode_PTag();

    /**
     * The meta object literal for the '<em><b>Case Sensitive</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPLICIT_NODE__CASE_SENSITIVE = eINSTANCE.getExplicitNode_CaseSensitive();

    /**
     * The meta object literal for the '<em><b>Expr</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPLICIT_NODE__EXPR = eINSTANCE.getExplicitNode_Expr();

    /**
     * The meta object literal for the '<em><b>Any Match</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPLICIT_NODE__ANY_MATCH = eINSTANCE.getExplicitNode_AnyMatch();

    /**
     * The meta object literal for the '{@link com.specmate.cause_effect_patterns.specDSL.impl.SubtreeImpl <em>Subtree</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.specmate.cause_effect_patterns.specDSL.impl.SubtreeImpl
     * @see com.specmate.cause_effect_patterns.specDSL.impl.SpecDSLPackageImpl#getSubtree()
     * @generated
     */
    EClass SUBTREE = eINSTANCE.getSubtree();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SUBTREE__NAME = eINSTANCE.getSubtree_Name();

    /**
     * The meta object literal for the '{@link com.specmate.cause_effect_patterns.specDSL.impl.TagImpl <em>Tag</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.specmate.cause_effect_patterns.specDSL.impl.TagImpl
     * @see com.specmate.cause_effect_patterns.specDSL.impl.SpecDSLPackageImpl#getTag()
     * @generated
     */
    EClass TAG = eINSTANCE.getTag();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TAG__NAME = eINSTANCE.getTag_Name();

    /**
     * The meta object literal for the '<em><b>Tagname</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TAG__TAGNAME = eINSTANCE.getTag_Tagname();

  }

} //SpecDSLPackage
