/**
 * generated by Xtext 2.17.1
 */
package com.specmate.cause_effect_patterns.internal.specDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Subtree</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.specmate.cause_effect_patterns.specDSL.Subtree#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see com.specmate.cause_effect_patterns.specDSL.SpecDSLPackage#getSubtree()
 * @model
 * @generated
 */
public interface Subtree extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' reference.
   * @see #setName(TreeTag)
   * @see com.specmate.cause_effect_patterns.specDSL.SpecDSLPackage#getSubtree_Name()
   * @model
   * @generated
   */
  TreeTag getName();

  /**
   * Sets the value of the '{@link com.specmate.cause_effect_patterns.specDSL.Subtree#getName <em>Name</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' reference.
   * @see #getName()
   * @generated
   */
  void setName(TreeTag value);

} // Subtree
