/**
 * generated by Xtext 2.17.1
 */
package com.specmate.cause_effect_patterns.internal.specDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Tag</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.specmate.cause_effect_patterns.specDSL.Tag#getName <em>Name</em>}</li>
 *   <li>{@link com.specmate.cause_effect_patterns.specDSL.Tag#getTagname <em>Tagname</em>}</li>
 * </ul>
 *
 * @see com.specmate.cause_effect_patterns.specDSL.SpecDSLPackage#getTag()
 * @model
 * @generated
 */
public interface Tag extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.specmate.cause_effect_patterns.specDSL.SpecDSLPackage#getTag_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.specmate.cause_effect_patterns.specDSL.Tag#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Tagname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Tagname</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tagname</em>' attribute.
   * @see #setTagname(String)
   * @see com.specmate.cause_effect_patterns.specDSL.SpecDSLPackage#getTag_Tagname()
   * @model
   * @generated
   */
  String getTagname();

  /**
   * Sets the value of the '{@link com.specmate.cause_effect_patterns.specDSL.Tag#getTagname <em>Tagname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tagname</em>' attribute.
   * @see #getTagname()
   * @generated
   */
  void setTagname(String value);

} // Tag
