/*
 * generated by Xtext 2.17.1
 */
package org.xtext.specmate.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.specmate.ui.internal.SpecmateActivator;

public class SpecDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SpecmateActivator.getInstance().getInjector("org.xtext.specmate.SpecDSL");
	}

}
