/**
 * generated by Xtext 2.17.1
 */
package org.xtext.specmate;

import org.xtext.specmate.AbstractSpecDSLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SpecDSLRuntimeModule extends AbstractSpecDSLRuntimeModule {
}
