/**
 * generated by Xtext 2.17.1
 */
package com.specmate.cause_effect_patterns.internal.specDSL.util;

import com.specmate.cause_effect_patterns.internal.specDSL.*;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.common.notify.impl.AdapterFactoryImpl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * The <b>Adapter Factory</b> for the model.
 * It provides an adapter <code>createXXX</code> method for each class of the model.
 * <!-- end-user-doc -->
 * @see com.specmate.cause_effect_patterns.specDSL.SpecDSLPackage
 * @generated
 */
public class SpecDSLAdapterFactory extends AdapterFactoryImpl
{
  /**
   * The cached model package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static SpecDSLPackage modelPackage;

  /**
   * Creates an instance of the adapter factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SpecDSLAdapterFactory()
  {
    if (modelPackage == null)
    {
      modelPackage = SpecDSLPackage.eINSTANCE;
    }
  }

  /**
   * Returns whether this factory is applicable for the type of the object.
   * <!-- begin-user-doc -->
   * This implementation returns <code>true</code> if the object is either the model's package or is an instance object of the model.
   * <!-- end-user-doc -->
   * @return whether this factory is applicable for the type of the object.
   * @generated
   */
  @Override
  public boolean isFactoryForType(Object object)
  {
    if (object == modelPackage)
    {
      return true;
    }
    if (object instanceof EObject)
    {
      return ((EObject)object).eClass().getEPackage() == modelPackage;
    }
    return false;
  }

  /**
   * The switch that delegates to the <code>createXXX</code> methods.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SpecDSLSwitch<Adapter> modelSwitch =
    new SpecDSLSwitch<Adapter>()
    {
      @Override
      public Adapter caseModel(Model object)
      {
        return createModelAdapter();
      }
      @Override
      public Adapter caseAbstractElement(AbstractElement object)
      {
        return createAbstractElementAdapter();
      }
      @Override
      public Adapter caseImport(Import object)
      {
        return createImportAdapter();
      }
      @Override
      public Adapter casePosDef(PosDef object)
      {
        return createPosDefAdapter();
      }
      @Override
      public Adapter casePOSTag(POSTag object)
      {
        return createPOSTagAdapter();
      }
      @Override
      public Adapter caseDepDef(DepDef object)
      {
        return createDepDefAdapter();
      }
      @Override
      public Adapter caseDepTag(DepTag object)
      {
        return createDepTagAdapter();
      }
      @Override
      public Adapter caseTreeDef(TreeDef object)
      {
        return createTreeDefAdapter();
      }
      @Override
      public Adapter caseTreeTag(TreeTag object)
      {
        return createTreeTagAdapter();
      }
      @Override
      public Adapter caseRule(Rule object)
      {
        return createRuleAdapter();
      }
      @Override
      public Adapter caseDependencyRule(DependencyRule object)
      {
        return createDependencyRuleAdapter();
      }
      @Override
      public Adapter caseNode(Node object)
      {
        return createNodeAdapter();
      }
      @Override
      public Adapter caseOptionNode(OptionNode object)
      {
        return createOptionNodeAdapter();
      }
      @Override
      public Adapter caseTreeNode(TreeNode object)
      {
        return createTreeNodeAdapter();
      }
      @Override
      public Adapter caseExplicitNode(ExplicitNode object)
      {
        return createExplicitNodeAdapter();
      }
      @Override
      public Adapter caseSubtree(Subtree object)
      {
        return createSubtreeAdapter();
      }
      @Override
      public Adapter caseTag(Tag object)
      {
        return createTagAdapter();
      }
      @Override
      public Adapter defaultCase(EObject object)
      {
        return createEObjectAdapter();
      }
    };

  /**
   * Creates an adapter for the <code>target</code>.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param target the object to adapt.
   * @return the adapter for the <code>target</code>.
   * @generated
   */
  @Override
  public Adapter createAdapter(Notifier target)
  {
    return modelSwitch.doSwitch((EObject)target);
  }


  /**
   * Creates a new adapter for an object of class '{@link com.specmate.cause_effect_patterns.specDSL.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.specmate.cause_effect_patterns.specDSL.Model
   * @generated
   */
  public Adapter createModelAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.specmate.cause_effect_patterns.specDSL.AbstractElement <em>Abstract Element</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.specmate.cause_effect_patterns.specDSL.AbstractElement
   * @generated
   */
  public Adapter createAbstractElementAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.specmate.cause_effect_patterns.specDSL.Import <em>Import</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.specmate.cause_effect_patterns.specDSL.Import
   * @generated
   */
  public Adapter createImportAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.specmate.cause_effect_patterns.specDSL.PosDef <em>Pos Def</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.specmate.cause_effect_patterns.specDSL.PosDef
   * @generated
   */
  public Adapter createPosDefAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.specmate.cause_effect_patterns.specDSL.POSTag <em>POS Tag</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.specmate.cause_effect_patterns.specDSL.POSTag
   * @generated
   */
  public Adapter createPOSTagAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.specmate.cause_effect_patterns.specDSL.DepDef <em>Dep Def</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.specmate.cause_effect_patterns.specDSL.DepDef
   * @generated
   */
  public Adapter createDepDefAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.specmate.cause_effect_patterns.specDSL.DepTag <em>Dep Tag</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.specmate.cause_effect_patterns.specDSL.DepTag
   * @generated
   */
  public Adapter createDepTagAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.specmate.cause_effect_patterns.specDSL.TreeDef <em>Tree Def</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.specmate.cause_effect_patterns.specDSL.TreeDef
   * @generated
   */
  public Adapter createTreeDefAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.specmate.cause_effect_patterns.specDSL.TreeTag <em>Tree Tag</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.specmate.cause_effect_patterns.specDSL.TreeTag
   * @generated
   */
  public Adapter createTreeTagAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.specmate.cause_effect_patterns.specDSL.Rule <em>Rule</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.specmate.cause_effect_patterns.specDSL.Rule
   * @generated
   */
  public Adapter createRuleAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.specmate.cause_effect_patterns.specDSL.DependencyRule <em>Dependency Rule</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.specmate.cause_effect_patterns.specDSL.DependencyRule
   * @generated
   */
  public Adapter createDependencyRuleAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.specmate.cause_effect_patterns.specDSL.Node <em>Node</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.specmate.cause_effect_patterns.specDSL.Node
   * @generated
   */
  public Adapter createNodeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.specmate.cause_effect_patterns.specDSL.OptionNode <em>Option Node</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.specmate.cause_effect_patterns.specDSL.OptionNode
   * @generated
   */
  public Adapter createOptionNodeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.specmate.cause_effect_patterns.specDSL.TreeNode <em>Tree Node</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.specmate.cause_effect_patterns.specDSL.TreeNode
   * @generated
   */
  public Adapter createTreeNodeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.specmate.cause_effect_patterns.specDSL.ExplicitNode <em>Explicit Node</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.specmate.cause_effect_patterns.specDSL.ExplicitNode
   * @generated
   */
  public Adapter createExplicitNodeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.specmate.cause_effect_patterns.specDSL.Subtree <em>Subtree</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.specmate.cause_effect_patterns.specDSL.Subtree
   * @generated
   */
  public Adapter createSubtreeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.specmate.cause_effect_patterns.specDSL.Tag <em>Tag</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.specmate.cause_effect_patterns.specDSL.Tag
   * @generated
   */
  public Adapter createTagAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for the default case.
   * <!-- begin-user-doc -->
   * This default implementation returns null.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @generated
   */
  public Adapter createEObjectAdapter()
  {
    return null;
  }

} //SpecDSLAdapterFactory
