/*
 * generated by Xtext 2.17.1
 */
package com.specmate.cause_effect_patterns.internal.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSpecDSLScopeProvider extends DelegatingScopeProvider {
}
