/**
 * generated by Xtext 2.17.1
 */
package org.xtext.specmate.scoping;

import org.xtext.specmate.scoping.AbstractSpecDSLScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class SpecDSLScopeProvider extends AbstractSpecDSLScopeProvider {
}
