/**
 * generated by Xtext 2.17.1
 */
package org.xtext.specmate.ui.contentassist;

import org.xtext.specmate.ui.contentassist.AbstractSpecDSLProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class SpecDSLProposalProvider extends AbstractSpecDSLProposalProvider {
}
