/**
 * generated by Xtext 2.17.1
 */
package org.xtext.specmate.ide;

import org.xtext.specmate.ide.AbstractSpecDSLIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class SpecDSLIdeModule extends AbstractSpecDSLIdeModule {
}
